version: '3.8'

services:
  # Development Database
  postgres-dev:
    image: postgres:14-alpine
    container_name: blog-engine-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_engine_dev
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/sql/init-dev.sql:/docker-entrypoint-initdb.d/init-dev.sql
    networks:
      - blog-engine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog_engine_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Testing Database
  postgres-test:
    image: postgres:14-alpine
    container_name: blog-engine-test-db
    restart: unless-stopped
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_engine_test
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5435:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/sql/init-test.sql:/docker-entrypoint-initdb.d/init-test.sql
    networks:
      - blog-engine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog_engine_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: blog-engine-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blog-engine-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: blog-engine-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blogengine.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - blog-engine-network
    depends_on:
      - postgres-dev
      - postgres-test

volumes:
  postgres_dev_data:
    driver: local
  postgres_test_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  blog-engine-network:
    driver: bridge 