version: '3.8'

services:
  postgres:
    build:
      context: ./scripts/docker/postgres
      dockerfile: Dockerfile
    container_name: tv_company_db
    environment:
      # PostgreSQL default settings
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      # Application database settings
      DB_USER: tv_company_user
      DB_PASSWORD: tv_company_pass
      DB_NAME: tv_company_db
    ports:
      - "5432:5432"
    volumes:
      # Persist data between container restarts
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount SQL scripts for easy access
      - ./sql:/docker-entrypoint-initdb.d/sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
