# Init docker-compose.yml

version: "3.8"

services:
  # PostgreSQL Database Service
  postgres:
    build:
      context: ./scripts/docker/postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Server Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-server
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "${WEB_HOST_PORT:-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app
    command: ["sh", "scripts/start-development-server.sh"]

# Define named volumes
volumes:
  postgres_data:
    driver: local

# Define networks
networks:
  app-network:
    driver: bridge
