# Generated by Django 5.0.2 on 2025-06-16 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "db_table": "authors",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="authors_email_76478b_idx"),
                    models.Index(fields=["name"], name="authors_name_e12c66_idx"),
                    models.Index(
                        fields=["created_at"], name="authors_created_5268e2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="categories_name_98d7d5_idx"),
                    models.Index(
                        fields=["created_at"], name="categories_created_7b3de3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The author of this book",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.author",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="Categories this book belongs to",
                        related_name="books",
                        to="books.category",
                    ),
                ),
            ],
            options={
                "db_table": "books",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["isbn"], name="books_isbn_ce4a1a_idx"),
                    models.Index(fields=["title"], name="books_title_7a737c_idx"),
                    models.Index(
                        fields=["created_at"], name="books_created_a6d93f_idx"
                    ),
                ],
            },
        ),
    ]
