name: Python Lint & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'docker-learning/practice/docker-compose-practice/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker-learning/practice/docker-compose-practice/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd docker-learning/practice/docker-compose-practice
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run black
        run: cd docker-learning/practice/docker-compose-practice && black . --check
      - name: Run isort
        run: cd docker-learning/practice/docker-compose-practice && isort . --check-only
      - name: Run flake8
        run: cd docker-learning/practice/docker-compose-practice && flake8 .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd docker-learning/practice/docker-compose-practice
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run tests
        run: cd docker-learning/practice/docker-compose-practice && pytest -v 