name: Deploy (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: develop
        options:
          - develop
          - main
      branch:
        description: 'Branch to deploy'
        required: true
        type: string
        default: 'develop'
      dry-run:
        description: 'Dry-run?'
        required: true
        type: choice
        default: 'true'
        options:
          - 'true'
          - 'false'

env:
  PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
  PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
  PYTHONANYWHERE_WEBAPP_NAME: ${{ secrets.PYTHONANYWHERE_WEBAPP_NAME }}

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pythonanywhere-client

      - name: Deploy to PythonAnywhere
        if: github.event.inputs.dry-run == 'false'
        run: |
          echo "Deploying to PythonAnywhere..."
          echo "- Webapp: ${{ env.PYTHONANYWHERE_WEBAPP_NAME }}"
          echo "- Environment: ${{ github.event.inputs.environment }}"
          echo "- Branch: ${{ github.event.inputs.branch }}"

          # Create PythonAnywhere client
          python -c "
          from pythonanywhere_client import PythonAnywhereClient
          client = PythonAnywhereClient(
              username='${{ env.PYTHONANYWHERE_USERNAME }}',
              api_token='${{ env.PYTHONANYWHERE_API_TOKEN }}'
          )

          # Reload the web app
          client.reload_webapp('${{ env.PYTHONANYWHERE_WEBAPP_NAME }}')
          print('✅ Webapp reloaded successfully')
          "

      - name: Dry Run
        if: github.event.inputs.dry-run == 'true'
        run: |
          echo "🔍 Dry Run Mode"
          echo "=============="
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Webapp: ${{ env.PYTHONANYWHERE_WEBAPP_NAME }}"
          echo ""
          echo "✅ This was a dry run - no changes were made"
