name: "CI/CD: Test, Build, Deploy (Production)"
# Full CI/CD pipeline for docker-practice: test, build, push, and deploy to VPS
# Uses /docker-practice/Dockerfile and can use scripts from /docker-practice/scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docker-practice/**'
  push:
    branches:
      - main
    paths:
      - 'docker-practice/**'

env:
  DOCKER_IMAGE: docker-practice-app
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  shared-ci:
    uses: ./.github/workflows/shared-ci-jobs.yml
    with:
      target-branch: main
      skip-on-no-changes: false
      run-docker-compose: false
      container_name: docker-practice-app
      healthcheck_url: http://localhost:8000/health/
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

  build-and-push:
    needs: shared-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-practice
          file: ./docker-practice/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp docker-practice/docker-compose.yml deploy/
          cp docker-practice/scripts/docker/postgres/Dockerfile deploy/
          cp docker-practice/scripts/docker/postgres/create-user.sh deploy/
          cp docker-practice/local.env deploy/.env

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "deploy/"
          target: "/home/${{ secrets.VPS_USERNAME }}/app"
          script: |
            set -e
            cd /home/${{ secrets.VPS_USERNAME }}/app

            # Login to DockerHub
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            # Stop and remove old containers
            docker-compose down || true

            # Update environment variables
            echo "DJANGO_SETTINGS_MODULE=core.settings.production" >> .env
            echo "DB_HOST=postgres" >> .env
            echo "DB_PORT=5432" >> .env
            echo "DB_NAME=postgres" >> .env
            echo "DB_USER=postgres" >> .env
            echo "DB_PASSWORD=postgres" >> .env
            echo "ALLOWED_HOSTS=*" >> .env
            echo "DEBUG=False" >> .env
            echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env

            # Start services
            docker-compose up -d

            # Wait for services to be healthy
            echo "Waiting for services to be ready..."
            for i in {1..30}; do
              if curl -s http://localhost:8080/health/ | grep -q "ok"; then
                echo "Application is healthy"
                exit 0
              fi
              echo "Waiting for application to be healthy... (attempt $i/30)"
              sleep 2
            done
            echo "Application failed to become healthy after 60 seconds"
            exit 1

  health-check:
    needs: deploy
    uses: ./.github/workflows/shared-ci-jobs.yml
    with:
      target-branch: main
      container_name: docker-practice-app
      healthcheck_url: http://localhost:8080/health/
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
