name: Use Vars and Envs

on:
  workflow_dispatch:

jobs:
  use-vars-and-envs:
    runs-on: ubuntu-22.04
    steps:
      - name: Show GitHub context variables
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"

      - name: Show repository variable
        run: |
          echo "TEST_VAR: ${{ vars.TEST_VAR }}"

      - name: Show secret
        run: |
          echo "TEST_SECRET (last 4): ${TEST_SECRET: -4}"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}

      - name: Show Docker variables and secrets
        run: |
          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN (last 4): ${DOCKERHUB_TOKEN: -4}"
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD (last 4): ${DOCKER_PASSWORD: -4}"
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
